---
abstract: 'Transparently work in waveband, wavelength or filter'
author:
  - 'Tim Jenness <tjenness@cpan.org>'
  - 'Brad Cavanagh <b.cavanagh@jach.hawaii.edu>'
  - 'Alasdair Allan <aa@astro.ex.ac.uk>'
  - 'Tim Lister <tlister@lcogt.net>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.3
dynamic_config: 1
generated_by: 'Module::Build version 0.3901, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Astro-WaveBand
provides:
  Astro::WaveBand:
    file: lib/Astro/WaveBand.pm
    version: 0.08
resources:
  homepage: http://github.com/timj/perl-Astro-WaveBand/tree/master
  license: http://dev.perl.org/licenses/
  repository: git://github.com/timj/perl-Astro-WaveBand.git
version: 0.08
